name: microproject-us-congress Grading
'on':
  workflow_dispatch: {}
jobs:
  autograding:
    name: autograding
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      id: sr-checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: microproject-us-congress/requirements.txt
    - run: pip install -r microproject-us-congress/requirements.txt
    - name: Checkout release repository
      id: release-checkout
      uses: actions/checkout@v3
      with:
        repository: dsdiscovery/microprojects
        ref: microproject-us-congress
        path: release
    - name: Checkout cell replacer
      id: cell-replace-checkout
      uses: actions/checkout@v3
      with:
        repository: dsdiscovery/cell-replace
        path: cell-replace
    - name: Run cell-replace
      run: python cell-replace/cell-replace.py microproject-us-congress/microproject-us-congress.ipynb release/microproject-us-congress/microproject-us-congress.ipynb
    - name: Generate Test Script
      run: 'python3 -m jupyter2pytest microproject-us-congress/microproject-us-congress.ipynb "### TEST CASE for (.*)" microproject-us-congress/test_microproject-us-congress.py '
    - name: Generate Grading Artifacts
      run: cd microproject-us-congress && python3 test_microproject-us-congress.py && cd ..
    - name: Autograding
      id: autograding
      uses: illinois/autograding@v4
      with:
        path: microproject-us-congress/
        test_suite: autograding
        step_summary: true
        all_or_nothing: true
